# Configuración de MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/optica_molina_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=tupassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Puerto del servidor
server.port=8080
# Mercado Pago
mercadopago.access.token=APP_USR-TU-TOKEN-AQUI