# Configuración de MySQL con variables de entorno de Railway
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Puerto del servidor (opcional, por defecto es 8080)
server.port=8080

# Token de MercadoPago
mercadopago.access.token=APP_USR-5406276048692208-033110-b4c6975b964946b23cd44409abb031bb-840117118

String img = (String) item.get("thumbnail");
p.setImagenUrl(img.replace("-I.jpg", "-O.jpg")); // El -O suele ser de mejor calidad